"""baseline schema

Revision ID: 082d999d7910
Revises:
Create Date: 2025-12-22 23:26:56.716644

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "082d999d7910"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_results",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "url", name="uq_search_results_source_url"),
    )
    op.create_index(
        "ix_search_results_published_at", "search_results", ["published_at"], unique=False
    )
    op.create_index("ix_search_results_source", "search_results", ["source"], unique=False)
    op.create_table(
        "topics",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "keywords",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("ix_topics_created_at", "topics", ["created_at"], unique=False)
    op.create_index("ix_topics_name", "topics", ["name"], unique=False)
    op.create_table(
        "articles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("draft", "in_review", "published", "archived", name="article_status_enum"),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_articles_created_at", "articles", ["created_at"], unique=False)
    op.create_index("ix_articles_published_at", "articles", ["published_at"], unique=False)
    op.create_index("ix_articles_status", "articles", ["status"], unique=False)
    op.create_index("ix_articles_topic_id", "articles", ["topic_id"], unique=False)
    op.create_table(
        "email_threads",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("thread_id", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column(
            "participants",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "messages",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("open", "closed", "archived", name="email_thread_status_enum"),
            server_default="open",
            nullable=False,
        ),
        sa.Column("last_activity_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_email_threads_article_id", "email_threads", ["article_id"], unique=False)
    op.create_index(
        "ix_email_threads_last_activity_at", "email_threads", ["last_activity_at"], unique=False
    )
    op.create_index("ix_email_threads_status", "email_threads", ["status"], unique=False)
    op.create_index("ix_email_threads_thread_id", "email_threads", ["thread_id"], unique=False)
    op.create_table(
        "workflow_states",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "idea",
                "researching",
                "drafting",
                "reviewing",
                "published",
                name="workflow_state_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "state_data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "transitioned_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("transitioned_by", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["articles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_workflow_states_article_id", "workflow_states", ["article_id"], unique=False
    )
    op.create_index("ix_workflow_states_state", "workflow_states", ["state"], unique=False)
    op.create_index(
        "ix_workflow_states_transitioned_at", "workflow_states", ["transitioned_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_workflow_states_transitioned_at", table_name="workflow_states")
    op.drop_index("ix_workflow_states_state", table_name="workflow_states")
    op.drop_index("ix_workflow_states_article_id", table_name="workflow_states")
    op.drop_table("workflow_states")
    op.drop_index("ix_email_threads_thread_id", table_name="email_threads")
    op.drop_index("ix_email_threads_status", table_name="email_threads")
    op.drop_index("ix_email_threads_last_activity_at", table_name="email_threads")
    op.drop_index("ix_email_threads_article_id", table_name="email_threads")
    op.drop_table("email_threads")
    op.drop_index("ix_articles_topic_id", table_name="articles")
    op.drop_index("ix_articles_status", table_name="articles")
    op.drop_index("ix_articles_published_at", table_name="articles")
    op.drop_index("ix_articles_created_at", table_name="articles")
    op.drop_table("articles")
    op.drop_index("ix_topics_name", table_name="topics")
    op.drop_index("ix_topics_created_at", table_name="topics")
    op.drop_table("topics")
    op.drop_index("ix_search_results_source", table_name="search_results")
    op.drop_index("ix_search_results_published_at", table_name="search_results")
    op.drop_table("search_results")
    # ### end Alembic commands ###

    # Drop ENUM types
    op.execute("DROP TYPE IF EXISTS workflow_state_enum")
    op.execute("DROP TYPE IF EXISTS email_thread_status_enum")
    op.execute("DROP TYPE IF EXISTS article_status_enum")
